### ISSUE TITLE
version compatibility between js and PHP implementation?

### ISSUE THREAD

**Issue by aelgoa** [nullpunkt/lz-string-php#3] opened 2014-09-26 18:28 UTC
js: LZString.compressToBase64(document.getElementById('src').value);
php: $s=LZString::decompressFromBase64($_POST['s']);

value is caught by PHP script as intented with correct value. error happens in decompression:

<br />
<b>Notice</b>:  Uninitialized string offset: 1123 in <b>D:\babs\8.5\root\wwide\LZString.php</b> on line <b>354</b><br />
<br />
<b>Warning</b>:  strpos() [<a href='function.strpos'>function.strpos</a>]: Empty delimiter in <b>D:\babs\8.5\root\wwide\LZString.php</b> on line <b>354</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message '$c != $dictSize (133,128)' in D:\babs\8.5\root\wwide\LZString.php:313
Stack trace:
#0 D:\babs\8.5\root\wwide\LZString.php(380): LZString::decompress('???????????????...')
#1 D:\babs\8.5\root\wwide\wwc.php(6): LZString::decompressFromBase64('MQSwdgxgNgrgJgU...')
#2 {main}
  thrown in <b>D:\babs\8.5\root\wwide\LZString.php</b> on line <b>313</b><br />

**Comment by nuald** [comment] 2015-03-11 21:39
Looks like it's related to base64 encoding, 3rd party Base64 decode + LZString.decompress work correctly (so far at least, the original issue doesn't have 100% reproducibility).

**Comment by ACTech** [comment] 2015-05-05 00:25
If you're passing the base64 data directly via URL, the decoding process replaces the pluses with spaces which are not valid base64 characters. You may need to retrieve the parameter from the query string, then replace any spaces with pluses before base64 decode or decodeFromBase64.

**Comment by nullpunkt** [comment] 2016-02-28 14:33
Hi, i've completely rewritten the PHP component to match the current algorythm / ouput provided by the javascript component. The bug is fixed in version 1.1.0.

**Closed by nullpunkt** 2016-02-28 14:33 UTC

**Comment by mattpass** [comment] 2016-02-29 08:50
That's awesome - many thanks!! :+1: Definitely going to check this out.

**Comment by Tarekajaj** [comment] 2016-02-29 10:29
Awesome. just tested the new version and all the (too much errors) were gone.  ![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
